# File: .github/workflows/deploy.yml
name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Node.js CI"]  # Make sure this matches the `name:` in ci.yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download test output artifact
        uses: actions/download-artifact@v4
        with:
          name: test-logs  # ✅ Match artifact name from ci.yml
          path: ./artifact

      - name: Show contents of test-output.txt
        run: |
          echo "Test output from previous workflow:"
          cat ./artifact/test-output.txt