name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Node.js CI"]  # Make sure this matches ci.yml
    types:
      - completed

permissions:
  actions: read  # ✅ Needed to access artifacts from another workflow
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download test output artifact
        uses: actions/download-artifact@v4
        with:
          name: test-logs   # ✅ This must match the name in ci.yml
          path: ./artifact

      - name: Show contents of test-output.txt
        run: |
          echo "Test output from previous workflow:"
          cat ./artifact/test-output.txt
